x-networks: &networks
  networks:
    - default

services:
  elasticsearch:
    <<: *networks
    image: docker.elastic.co/elasticsearch/elasticsearch${ELASTIC_TAG:?}
    restart: unless-stopped
    container_name: elasticsearch
    environment: 
      CLI_JAVA_OPTS: "-Xms2g -Xmx2g"
      bootstrap.memory_lock: "true"
      discovery.type: "single-node"
      xpack.security.enabled: "false"
      xpack.security.enrollment.enabled: "false"
    volumes:
      - ./data:/data
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  kibana:
    <<: *networks
    image: docker.elastic.co/kibana/kibana${ELASTIC_TAG:?}
    restart: unless-stopped
    container_name: kibana
    environment:
      SERVER_NAME: ${SERVERNAME}
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: ${KEY}
    ports:
      - 5601:5601
    labels:
      - "traefik.enable=true"
    depends_on:
      - elasticsearch

networks:
  default:
    name: ${MYNET:?}
    external: true
