version: "3.8"
networks:
  default:
    name: ${MYNET}
    external: true

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    restart: unless-stopped
    container_name: elasticsearch
    environment: ['CLI_JAVA_OPTS=-Xms2g -Xmx2g','bootstrap.memory_lock=true','discovery.type=single-node','xpack.security.enabled=false', 'xpack.security.enrollment.enabled=false']
    volumes:
      - ./data:/data
    ports:
      - 9200:9200
    networks:
      - default
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    environment:
      SERVER_NAME: ${SERVERNAME}
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: ${KEY}
    ports:
      - 5601:5601
    labels:
      - "traefik.enable=true"
    networks:
      - default
    depends:
      - elasticsearch
