version: "3.8"
services:
  postgres:
    image: ubuntu/postgres
    #image: postgres:alpine
    container_name: postgres_alpine
    environment:
      - POSTGRES_USER=${USER_NAME}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data

