auth:
  type: DISABLED
kafka:
  clusters:
  - 
    name: test
    bootstrapServers: kafka:9092
    schemaRegistry: http://schema-registry:8081
    properties: {}
    readOnly: false
rbac:
  roles: []
webclient: {}
