version: "3.8"
networks:
  alsinet:
    external: true
services:
  gitea:
    image: gitea/gitea:latest
    restart: unless-stopped
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=postgres
      - DB_NAME=${DB_NAME}
      - DB_USER=${USER_NAME}
      - DB_PASSWD=${PASSWORD}
      - TZ=${TINEZONE}
    volumes:
      - ./data:/data
    ports:
      - "3000:3000"
      - "22:22"
    labels:
      - "traefik.enable=true"
    networks:
      - alsinet
