networks:
  default:
    name: ${MYNET:?}
    external: true

services:
  keycloak:
    image: bitnami/keycloak:${KEYCLOAK_TAG:?}
    container_name: keycloak
    restart: unless-stopped
    environment:
      - KEYCLOAK_ADMIN_USER=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_DATABASE_VENDOR=${KEYCLOAK_DATABASE_VENDOR}
      - KEYCLOAK_DATABASE_HOST=${KEYCLOAK_DATABASE_HOST}
      - KEYCLOAK_DATABASE_PORT=${KEYCLOAK_DATABASE_PORT}
      - KEYCLOAK_DATABASE_NAME=${KEYCLOAK_DATABASE_NAME}
      - KEYCLOAK_DATABASE_USER=${KEYCLOAK_DATABASE_USER}
      - KEYCLOAK_DATABASE_PASSWORD=${KEYCLOAK_DATABASE_PASSWORD}
    ports:
      - 0.0.0.0:8080:8080
    labels:
      - "traefik.enable=false"
    networks:
      - default
