networks:
  default:
    name: ${MYNET}
    external: true

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
      - TRAEFIKHOSTNAME=${TRAEFIKHOSTNAME}
      - GITEAHOSTNAME=${GITEAHOSTNAME}
      - JENKINSHOSTNAME=${JENKINSHOSTNAME}
      - KAFKA_UIHOSTNAME=${KAFKA_UIHOSTNAME}
      - KIBANAHOSTNAME=${KIBANAHOSTNAME}
      - CERTNAME=${CERTNAME}
    volumes:
      - /var/run/podman.sock:/var/run/docker.sock:rw
      - ./data:/home/traefik/
      - /etc/localtime:/etc/localtime:ro
      - ./static-conf.toml:/traefik.toml
      - ./acme.json:/acme.json
    ports:
      - 80:80
      - 443:443
    labels:
      - "traefik.enable=true"
    networks:
      - default
