x-networks: &networks
  networks:
    - default

services:
  traefik:
    <<: *networks
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE:?}
      TRAEFIKHOSTNAME: ${TRAEFIKHOSTNAME:?}
      GITEAHOSTNAME: ${GITEAHOSTNAME:?}
      JENKINSHOSTNAME: ${JENKINSHOSTNAME:?}
      KAFKA_UIHOSTNAME: ${KAFKA_UIHOSTNAME:?}
      KIBANAHOSTNAME: ${KIBANAHOSTNAME:?}
      ARANGOHOSTNAME: ${ARANGOHOSTNAME:?}
      MONGOEXPRESSHOSTNAME: ${MONGOEXPRESSHOSTNAME:?}
      MINIOHOSTNAME: ${MINIOHOSTNAME:?}
      KEYCLOAKHOSTNAME: ${KEYCLOAKHOSTNAME:?}
      CERTNAME: ${CERTNAME}
      CF_API_EMAIL: ${CF_API_EMAIL}
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
      TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL: ${CF_API_EMAIL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./data:/home/traefik/
      - /etc/localtime:/etc/localtime:ro
      - ./static-conf.toml:/traefik.toml
      - ./acme.json:/acme.json
    ports:
      # - 0.0.0.0:80:80
      - 0.0.0.0:443:443

networks:
  default:
    name: ${MYNET:?}
    external: true
