version: "3.8"
networks:
    alsinet:
        external: true
        name: "${MYNET}"
services:
        traefik:
            image: traefik:latest
            container_name: traefik
            ports:
                    - 80:80
                    - 443:443
            labels:
                    - traefik.enable=true
            networks:
                    - "${MYNET}"
            environment:
                    - TZ=Europe/Moscow
                    - TRAEFICHOSTNAME
                    - GITEAHOSTNAME
                    - CERTNAME
            volumes:
                    - /var/run/docker.sock:/var/run/docker.sock:rw
                    - ./data:/home/traefik/
                    - /etc/localtime:/etc/localtime:ro
                    - ./static-conf.toml:/traefik.toml
                    - ./acme.json:/acme.json
            restart: unless-stopped


