version: "3.8"
networks:
  default:
    name: ${MYNET}
    external: true

services:
  traefik:
    image: traefik:3.0
    container_name: traefik
    restart: always
    environment:
      - TZ=${TIMEZONE}
      - TRAEFIKHOSTNAME
      - GITEAHOSTNAME
      - JENKINSHOSTNAME
      - KAFKA_UIHOSTNAME
      - KIBANAHOSTNAME
      - CERTNAME
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./data:/home/traefik/
      - /etc/localtime:/etc/localtime:ro
      - ./static-conf.toml:/traefik.toml
      - ./acme.json:/acme.json
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"
    networks:
      - default
