version: "3.8"
networks:
  alsinet:
    external: true
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
      - TRAEFICHOSTNAME
      - GITEAHOSTNAME
      - JENKINSHOSTNAME
      - CERTNAME
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./data:/home/traefik/
      - /etc/localtime:/etc/localtime:ro
      - ./static-conf.toml:/traefik.toml
      - ./acme.json:/acme.json
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"
    networks:
      - "${MYNET}"
