networks:
  default:
    name: ${MYNET}
    external: true

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE:?}
      TRAEFIKHOSTNAME: ${TRAEFIKHOSTNAME:?}
      GITEAHOSTNAME: ${GITEAHOSTNAME:?}
      JENKINSHOSTNAME: ${JENKINSHOSTNAME:?}
      KAFKA_UIHOSTNAME: ${KAFKA_UIHOSTNAME:?}
      KIBANAHOSTNAME: ${KIBANAHOSTNAME:?}
      ARANGOHOSTNAME: ${ARANGOHOSTNAME:?}
      MONGOEXPRESSHOSTNAME: ${MONGOEXPRESSHOSTNAME:?}
      CERTNAME: ${CERTNAME}
      CF_API_EMAIL: ${CF_API_EMAIL}
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
      TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL: ${CF_API_EMAIL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./data:/home/traefik/
      - /etc/localtime:/etc/localtime:ro
      - ./static-conf.toml:/traefik.toml
      - ./acme.json:/acme.json
    ports:
      - 80:80
      - 443:443
    labels:
      - "traefik.enable=true"
    networks:
      - default
