version: "3.8"
networks:
  alsinet:
    external: true
services:
  jenkins:
    image: jenkins/jenkins 
    restart: always
    privileged: true
    ports:
      - 8080:8080
      - 50000:50000  
    networks:
      - alsinet
    labels:
        - "traefik.enable=true"
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:ro
