version: "3.8"
networks:
  alsinet:
    external: true
services:
  jenkins:
    image: jenkins/jenkins 
    restart: always
    privileged: true
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000  
    networks:
      - alsinet
    labels:
        - "traefik.enable=true"
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=$TZ
      # - JENKINS_OPTS="--prefix=/jenkins"
  agent:
    image: jenkins/ssh-agent:jdk11
    privileged: true
    user: root
    container_name: agent
    networks:
      - alsinet
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${SSHPUBKEY}

