networks:
  default:
    name: ${MYNET:?}
    external: true

services:
  jenkins:
    image: jenkins/jenkins 
    restart: unless-stopped
    container_name: jenkins
    privileged: true
    environment:
      - TZ=${TIMEZONE}
      # - JENKINS_OPTS="--prefix=/jenkins"
    volumes:
      - ./data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8080:8080"
      - "50000:50000"
    labels:
      - "traefik.enable=true"
    networks:
      - default
    extra_hosts:
      - ${GITEA_HOST}

  # agent:
  #   image: jenkins/ssh-agent:jdk11
  #   container_name: agent
  #   restart: unless-stopped
  #   privileged: true
  #   user: root
  #   environment:
  #     - JENKINS_AGENT_SSH_PUBKEY=${SSHPUBKEY}
  #   networks:
  #     - local
  #   expose:
  #     - 22
