x-networks: &networks
  networks:
    - default
x-labels: &enable_traefik
  labels:
    - traefik.enable=true

services:
  minio:
    <<: [*networks, &enable_traefik]
    container_name: minio
    image: minio/minio${MINIO_TAG:?}
    restart: unless-stopped
    volumes:
      - ./data:/data
    env_file:
      - .env
    ports:
      - 0.0.0.0:9000:9000
      - 0.0.0.0:9001:9001
    command: server --console-address ":9001" /data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:?}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:?}

networks:
  default:
    name: ${MYNET:?}
    external: true
