version: "3.8"
networks:
  alsinet:
    external: true
services:
  minio:
    image: minio/minio
    restart: unless-stopped
    container_name: minio
    volumes:
      - ./data:/data
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data
    networks:
      - alsinet
