networks:
  default:
    name: ${MYNET}
    external: true
services:
  minio:
    container_name: minio
    image: minio/minio:latest
    restart: unless-stopped
    volumes:
      - ./data:/data
    env_file:
      - .env
    ports:
      - 9000:9000
      - 9001:9001
    command: server --console-address ":9001" /data
    networks:
      - default
