services:
  kafka:
    environment:
      # Listeners
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,INTER_BROKER://:9094,EXTERNAL://:9096"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,INTER_BROKER://localhost:9094,EXTERNAL://${ADVERTISED_ADDRESS:?}:9096"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTER_BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT"

      # Clients
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN

      # Unset variables
      KAFKA_LISTENER_NAME_OAUTH_PLAIN_SASL_JAAS_CONFIG: ""
      KAFKA_SASL_OAUTHBEARER_JWKS_ENDPOINT_URL: ""
      KAFKA_LISTENER_NAME_OAUTH_OAUTHBEARER_SASL_JAAS_CONFIG: ""
      KAFKA_LISTENER_NAME_OAUTH_OAUTHBEARER_SASL_SERVER_CALLBACK_HANDLER_CLASS: ""

