version: "3.8"
networks:
  default:
    name: ${MYNET}
    external: true

services:
  zookeeper:
    restart: unless-stopped
    # image: docker.io/bitnami/zookeeper:latest
    image: zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
    # for bitnami
    # volumes:
    #   - ./zookeeper_data:/bitnami
    # environment:
    #   - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - default

  kafka:
    image: bitnami/kafka:3.5
    restart: unless-stopped
    container_name: kafka
    volumes:
      - ./data:/data
    ports:
      - 9092:9092
      - 19092:19092
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://kafka:19092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://kafka:19092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - TZ=${TIMEZONE}
    depends_on:
      - zookeeper
    networks:
      - default

  kafka-ui:
    restart: unless-stopped
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    ports:
      - 8080:8080
    environment:
      -  DYNAMIC_CONFIG_ENABLED=true
    volumes:
      - ./kui/config.yml:/etc/kafkaui/dynamic_config.yaml
    depends_on:
      - kafka
    labels:
      - "traefik.enable=true"
    networks:
      - default
