version: "3.8"
networks:
  alsinet:
    external: true
services:
  zookeeper:
    restart: unless-stopped
    image: docker.io/bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - 2181:2181
    volumes:
      - ./zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - alsinet        
  kafka:
    image: bitnami/kafka:3.5
    restart: unless-stopped
    container_name: kafka
    volumes:
      - ./data:/data
    ports:
      - 9092:9092
      - 19092:19092
        #expose:
        #      - 9093
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://kafka:19092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://kafka:19092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - TZ=Europe/Istanbul
    depends_on:
      - zookeeper    
    networks:
      - alsinet
  kafka-ui:
    restart: unless-stopped
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    ports:
      - 8081:8080
    environment:
      -  DYNAMIC_CONFIG_ENABLED=true
    volumes:
      - ./kui/config.yml:/etc/kafkaui/dynamic_config.yaml
    depends_on:
      - kafka
    networks:
      - alsinet
