networks:
  default:
    name: ${MYNET:?}
    external: true

services:
  postgres:
    image: postgres:${POSTGRES_TAG:?}
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${USER_NAME:?}
      POSTGRES_PASSWORD: ${PASSWORD:?}
      POSTGRES_DB: ${DB_NAME:?}
      TZ: ${TIMEZONE:?}
    volumes:
      - ./data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 5432:5432
    # labels:
    #   - "traefik.enable=false"
    networks:
      - default
