version: '3'
networks:
    alsinet:
            external: true
    internal:
            external: false
services:
        postgres:
            image: postgres:latest
            container_name: postgres
            restart: always
            environment:
                    - POSTGRES_USER=${user_name}
                    - POSTGRES_PASSWORD=${password}
                    - POSTGRES_DB=${db_name}
            labels:
                    - "traefik.enable=false"
            networks:
                    - alsinet
                    - internal
            volumes:
                    - ./data:/var/lib/postgresql/data
            ports:
                    - "5432:5432"
