networks:
  default:
    name: ${MYNET:?}
    external: true

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USER_NAME:?}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD:?}
    ports:
      - 27017:27017
    networks:
      - default

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    container_name: mongo-express
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_USER_NAME:?}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_PASSWORD:?}
      ME_CONFIG_MONGODB_URL: mongodb://${USER_NAME:?}:${PASSWORD:?}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    labels:
      - "traefik.enable=true"
    depends_on:
      - mongo
    networks:
      - default