networks:
  default:
    name: ${MYNET:?}
    external: true
services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    # command: redis-server --save 500 1 --loglevel debug --requirepass $REDIS_PWD
    # command: redis-server --save 20 1 --loglevel notice
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PWD
    networks:
      - default
    volumes:
      - ./cache:/data

